openapi: 3.0.3
info:
  title: TruckTrack Driver Mobile API
  description: API endpoints consumed by the Driver Mobile App
  version: 1.0.0
  contact:
    name: TruckTrack Team

servers:
  - url: https://api.trucktrack.com
    description: Production
  - url: http://localhost:8000
    description: Local development

tags:
  - name: Auth
    description: Authentication endpoints
  - name: Driver
    description: Driver profile and status
  - name: GPS
    description: GPS position tracking
  - name: Trips
    description: Trip management
  - name: Messages
    description: Messaging with dispatch
  - name: Notifications
    description: Push notification management

paths:
  # ==================== AUTH ====================
  /auth/login:
    post:
      tags: [Auth]
      summary: Driver login
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/refresh:
    post:
      tags: [Auth]
      summary: Refresh access token
      operationId: refreshToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
      responses:
        '200':
          description: Token refreshed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid or expired refresh token

  /auth/logout:
    post:
      tags: [Auth]
      summary: Logout driver
      operationId: logout
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Logout successful

  # ==================== DRIVER ====================
  /drivers/me:
    get:
      tags: [Driver]
      summary: Get current driver profile
      operationId: getDriverProfile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Driver profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DriverProfile'
        '401':
          description: Unauthorized

  /drivers/me/status:
    get:
      tags: [Driver]
      summary: Get driver status
      operationId: getDriverStatus
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DriverStatus'

    put:
      tags: [Driver]
      summary: Update driver status
      operationId: updateDriverStatus
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStatusRequest'
      responses:
        '200':
          description: Status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DriverStatus'
        '400':
          description: Invalid status transition

  /drivers/me/fcm-token:
    post:
      tags: [Driver]
      summary: Register FCM token for push notifications
      operationId: registerFcmToken
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FcmTokenRequest'
      responses:
        '204':
          description: Token registered

    delete:
      tags: [Driver]
      summary: Unregister FCM token
      operationId: unregisterFcmToken
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Token unregistered

  # ==================== GPS ====================
  /gps/positions:
    post:
      tags: [GPS]
      summary: Submit GPS positions (batch)
      operationId: submitPositions
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PositionBatch'
      responses:
        '202':
          description: Positions accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PositionBatchResponse'
        '400':
          description: Invalid position data

  # ==================== TRIPS ====================
  /drivers/me/trips:
    get:
      tags: [Trips]
      summary: Get driver's assigned trips
      operationId: getDriverTrips
      security:
        - bearerAuth: []
      parameters:
        - name: date
          in: query
          description: Filter by date (YYYY-MM-DD), defaults to today
          schema:
            type: string
            format: date
        - name: status
          in: query
          description: Filter by status
          schema:
            type: string
            enum: [PENDING, IN_PROGRESS, COMPLETED, CANCELLED]
      responses:
        '200':
          description: List of trips
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trip'

  /trips/{tripId}:
    get:
      tags: [Trips]
      summary: Get trip details
      operationId: getTripDetails
      security:
        - bearerAuth: []
      parameters:
        - name: tripId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Trip details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
        '404':
          description: Trip not found

  /trips/{tripId}/start:
    post:
      tags: [Trips]
      summary: Start a trip
      operationId: startTrip
      security:
        - bearerAuth: []
      parameters:
        - name: tripId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Trip started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
        '400':
          description: Cannot start trip (wrong status)

  /trips/{tripId}/complete:
    post:
      tags: [Trips]
      summary: Complete a trip
      operationId: completeTrip
      security:
        - bearerAuth: []
      parameters:
        - name: tripId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Trip completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
        '400':
          description: Cannot complete trip (wrong status)

  # ==================== MESSAGES ====================
  /drivers/me/messages:
    get:
      tags: [Messages]
      summary: Get messages with dispatch
      operationId: getMessages
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 50
        - name: since
          in: query
          description: Get messages since timestamp
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: List of messages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessagePage'

    post:
      tags: [Messages]
      summary: Send message to dispatch
      operationId: sendMessage
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageRequest'
      responses:
        '201':
          description: Message sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'

  /messages/{messageId}/read:
    put:
      tags: [Messages]
      summary: Mark message as read
      operationId: markMessageRead
      security:
        - bearerAuth: []
      parameters:
        - name: messageId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Message marked as read

  # ==================== NOTIFICATIONS ====================
  /drivers/me/notifications:
    get:
      tags: [Notifications]
      summary: Get notification history
      operationId: getNotifications
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
        - name: unreadOnly
          in: query
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: List of notifications
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationPage'

  /notifications/{notificationId}/read:
    put:
      tags: [Notifications]
      summary: Mark notification as read
      operationId: markNotificationRead
      security:
        - bearerAuth: []
      parameters:
        - name: notificationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Notification marked as read

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # Auth
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8

    RefreshRequest:
      type: object
      required: [refreshToken]
      properties:
        refreshToken:
          type: string

    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        expiresIn:
          type: integer
          description: Seconds until access token expires
        user:
          $ref: '#/components/schemas/DriverProfile'

    # Driver
    DriverProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string
        role:
          type: string
          enum: [DRIVER]
        truckId:
          type: string
          format: uuid
        truckName:
          type: string
        isActive:
          type: boolean

    DriverStatus:
      type: object
      properties:
        status:
          type: string
          enum: [AVAILABLE, IN_DELIVERY, ON_BREAK, OFF_DUTY]
        updatedAt:
          type: string
          format: date-time

    UpdateStatusRequest:
      type: object
      required: [status]
      properties:
        status:
          type: string
          enum: [AVAILABLE, IN_DELIVERY, ON_BREAK, OFF_DUTY]

    FcmTokenRequest:
      type: object
      required: [token, platform]
      properties:
        token:
          type: string
        platform:
          type: string
          enum: [IOS, ANDROID]

    # GPS
    Position:
      type: object
      required: [latitude, longitude, accuracy, timestamp]
      properties:
        latitude:
          type: number
          format: double
          minimum: -90
          maximum: 90
        longitude:
          type: number
          format: double
          minimum: -180
          maximum: 180
        accuracy:
          type: number
          format: float
          minimum: 0
        speed:
          type: number
          format: float
          minimum: 0
        heading:
          type: number
          format: float
          minimum: 0
          maximum: 360
        altitude:
          type: number
          format: float
        timestamp:
          type: string
          format: date-time

    PositionBatch:
      type: object
      required: [positions]
      properties:
        truckId:
          type: string
          format: uuid
        positions:
          type: array
          items:
            $ref: '#/components/schemas/Position'
          minItems: 1
          maxItems: 100

    PositionBatchResponse:
      type: object
      properties:
        accepted:
          type: integer
        rejected:
          type: integer

    # Trips
    Trip:
      type: object
      properties:
        id:
          type: string
          format: uuid
        pickupAddress:
          type: string
        pickupLat:
          type: number
          format: double
        pickupLng:
          type: number
          format: double
        deliveryAddress:
          type: string
        deliveryLat:
          type: number
          format: double
        deliveryLng:
          type: number
          format: double
        clientName:
          type: string
        clientPhone:
          type: string
        scheduledTime:
          type: string
          format: date-time
        status:
          type: string
          enum: [PENDING, IN_PROGRESS, COMPLETED, CANCELLED]
        notes:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    # Messages
    Message:
      type: object
      properties:
        id:
          type: string
          format: uuid
        senderId:
          type: string
          format: uuid
        senderType:
          type: string
          enum: [DRIVER, DISPATCH]
        senderName:
          type: string
        content:
          type: string
        timestamp:
          type: string
          format: date-time
        isRead:
          type: boolean

    MessagePage:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Message'
        page:
          type: integer
        size:
          type: integer
        totalElements:
          type: integer
        totalPages:
          type: integer

    SendMessageRequest:
      type: object
      required: [content]
      properties:
        content:
          type: string
          maxLength: 1000

    # Notifications
    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum: [ALERT, GEOFENCE, MESSAGE, SYSTEM]
        title:
          type: string
        body:
          type: string
        data:
          type: object
          additionalProperties: true
        receivedAt:
          type: string
          format: date-time
        isRead:
          type: boolean
        actionUrl:
          type: string

    NotificationPage:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Notification'
        page:
          type: integer
        size:
          type: integer
        totalElements:
          type: integer
        totalPages:
          type: integer

    # Errors
    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string
