package com.trucktrack.gateway.filter;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.cloud.gateway.filter.GatewayFilter;
import org.springframework.cloud.gateway.filter.factory.AbstractGatewayFilterFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.server.reactive.ServerHttpRequest;
import org.springframework.http.server.reactive.ServerHttpResponse;
import org.springframework.stereotype.Component;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

import javax.crypto.SecretKey;
import java.util.Base64;

/**
 * JWT Authentication Filter for API Gateway
 * T034: Implement JWT token validation in api-gateway JwtAuthenticationFilter.java
 */
@Component
public class JwtAuthenticationFilter extends AbstractGatewayFilterFactory<JwtAuthenticationFilter.Config> {

    // Prefer a Base64 encoded 512-bit (64 bytes) secret in production, e.g. generated by:
    // openssl rand -base64 64
    @Value("${jwt.secret:changeme-this-should-be-a-very-long-secret-key-for-production}")
    private String secret;

    public JwtAuthenticationFilter() {
        super(Config.class);
    }

    @Override
    public GatewayFilter apply(Config config) {
        return (exchange, chain) -> {
            ServerHttpRequest request = exchange.getRequest();

            // Skip authentication for login and health check endpoints
            if (isPublicPath(request.getPath().toString())) {
                return chain.filter(exchange);
            }

            // Extract Authorization header
            if (!request.getHeaders().containsKey(HttpHeaders.AUTHORIZATION)) {
                return onError(exchange, "Missing authorization header", HttpStatus.UNAUTHORIZED);
            }

            String authHeader = request.getHeaders().getFirst(HttpHeaders.AUTHORIZATION);
            if (authHeader == null || !authHeader.startsWith("Bearer ")) {
                return onError(exchange, "Invalid authorization header format", HttpStatus.UNAUTHORIZED);
            }

            String token = authHeader.substring(7); // Remove "Bearer " prefix

            try {
                // Build the SecretKey from configured secret.
                // Expectation: 'secret' is Base64-encoded 64 bytes (512 bits). If it's not Base64,
                // we fallback to the raw bytes but enforce the minimum length.
                byte[] keyBytes;
                try {
                    keyBytes = Base64.getDecoder().decode(secret);
                } catch (IllegalArgumentException e) {
                    // not valid base64, use raw bytes
                    keyBytes = secret.getBytes();
                }

                // Enforce minimum key length for HS512 (512 bits = 64 bytes)
                if (keyBytes.length < 64) {
                    return onError(exchange, "JWT signing key too short: must be at least 512 bits (64 bytes). Configure a Base64 512-bit key.", HttpStatus.INTERNAL_SERVER_ERROR);
                }

                SecretKey key = Keys.hmacShaKeyFor(keyBytes);

                // Parse and validate JWT using the parser API
                Claims claims = Jwts.parser()
                        .setSigningKey(key)
                        .build()
                        .parseSignedClaims(token)
                        .getPayload();

                // Add user information to request headers for downstream services
                ServerHttpRequest modifiedRequest = request.mutate()
                        .header("X-User-Id", claims.get("userId", String.class))
                        .header("X-Username", claims.getSubject())
                        .header("X-User-Role", claims.get("role", String.class))
                        .build();

                return chain.filter(exchange.mutate().request(modifiedRequest).build());

            } catch (Exception e) {
                return onError(exchange, "Invalid or expired JWT token: " + e.getMessage(), HttpStatus.UNAUTHORIZED);
            }
        };
    }

    /**
     * Check if the requested path is public (no authentication required)
     */
    private boolean isPublicPath(String path) {
        return path.startsWith("/auth/") ||
                path.startsWith("/actuator/health") ||
                path.startsWith("/swagger-ui") ||
                path.startsWith("/v3/api-docs");
    }

    /**
     * Handle authentication errors
     */
    private Mono<Void> onError(ServerWebExchange exchange, String message, HttpStatus status) {
        ServerHttpResponse response = exchange.getResponse();
        response.setStatusCode(status);
        response.getHeaders().add(HttpHeaders.CONTENT_TYPE, "application/json");
        String errorResponse = String.format("{" + "\"error\":\"%s\",\"message\":\"%s\"}" ,
                status.getReasonPhrase(), message);
        return response.writeWith(Mono.just(response.bufferFactory().wrap(errorResponse.getBytes())));
    }

    public static class Config {
        // Configuration properties (if needed)
    }
}
