openapi: 3.0.3
info:
  title: Admin Users API
  description: User management endpoints for administrators
  version: 1.0.0

servers:
  - url: http://localhost:8000/auth/v1/admin
    description: API Gateway (local)

security:
  - bearerAuth: []

paths:
  /users:
    get:
      summary: List all users
      operationId: listUsers
      tags: [Users]
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
        - $ref: '#/components/parameters/sort'
        - name: search
          in: query
          schema:
            type: string
          description: Search by name or email
        - name: role
          in: query
          schema:
            $ref: '#/components/schemas/UserRole'
        - name: isActive
          in: query
          schema:
            type: boolean
      responses:
        '200':
          description: Paginated list of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedUserResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

    post:
      summary: Create a new user
      operationId: createUser
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created, activation email sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '409':
          description: Email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users/{userId}:
    get:
      summary: Get user by ID
      operationId: getUser
      tags: [Users]
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update user
      operationId: updateUser
      tags: [Users]
      parameters:
        - $ref: '#/components/parameters/userId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFound'

  /users/{userId}/deactivate:
    post:
      summary: Deactivate user account
      operationId: deactivateUser
      tags: [Users]
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '200':
          description: User deactivated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Cannot deactivate last admin or self
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          $ref: '#/components/responses/NotFound'

  /users/{userId}/reactivate:
    post:
      summary: Reactivate user account
      operationId: reactivateUser
      tags: [Users]
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '200':
          description: User reactivated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          $ref: '#/components/responses/NotFound'

  /users/{userId}/resend-activation:
    post:
      summary: Resend activation email
      operationId: resendActivation
      tags: [Users]
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '200':
          description: Activation email sent
        '400':
          description: User already activated
        '404':
          $ref: '#/components/responses/NotFound'

  /users/{userId}/groups:
    get:
      summary: Get user's assigned groups
      operationId: getUserGroups
      tags: [Users]
      parameters:
        - $ref: '#/components/parameters/userId'
      responses:
        '200':
          description: List of group IDs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: uuid
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update user's group assignments
      operationId: updateUserGroups
      tags: [Users]
      parameters:
        - $ref: '#/components/parameters/userId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                format: uuid
      responses:
        '200':
          description: Groups updated
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    userId:
      name: userId
      in: path
      required: true
      schema:
        type: string
        format: uuid
    page:
      name: page
      in: query
      schema:
        type: integer
        default: 0
    size:
      name: size
      in: query
      schema:
        type: integer
        default: 25
        enum: [10, 25, 50, 100]
    sort:
      name: sort
      in: query
      schema:
        type: string
        example: "lastName,asc"

  schemas:
    UserRole:
      type: string
      enum: [ADMIN, FLEET_MANAGER, DRIVER, VIEWER]

    CreateUserRequest:
      type: object
      required: [email, password, firstName, lastName, role]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
          description: "Min 8 chars, 1 uppercase, 1 lowercase, 1 digit"
        firstName:
          type: string
          maxLength: 100
        lastName:
          type: string
          maxLength: 100
        role:
          $ref: '#/components/schemas/UserRole'
        groupIds:
          type: array
          items:
            type: string
            format: uuid

    UpdateUserRequest:
      type: object
      properties:
        firstName:
          type: string
          maxLength: 100
        lastName:
          type: string
          maxLength: 100
        email:
          type: string
          format: email
        role:
          $ref: '#/components/schemas/UserRole'

    UserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        role:
          $ref: '#/components/schemas/UserRole'
        isActive:
          type: boolean
        lastLogin:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        groupIds:
          type: array
          items:
            type: string
            format: uuid

    PagedUserResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/UserResponse'
        totalElements:
          type: integer
        totalPages:
          type: integer
        size:
          type: integer
        number:
          type: integer

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time

  responses:
    Unauthorized:
      description: Missing or invalid JWT token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Forbidden:
      description: User does not have ADMIN role
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ValidationError:
      description: Validation failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
