openapi: 3.1.0
info:
  title: TruckTrack Cache Management API
  description: |
    API endpoints for cache management and monitoring.
    Most caching is transparent to clients, but these endpoints allow
    administrators to monitor cache health and manually invalidate when needed.
  version: 1.0.0

servers:
  - url: /admin/cache
    description: Admin cache management endpoints

paths:
  /stats:
    get:
      summary: Get cache statistics
      description: Returns current cache hit/miss statistics and memory usage
      operationId: getCacheStats
      tags:
        - Cache Management
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Cache statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CacheStats'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - requires FLEET_MANAGER role

  /invalidate/{cacheType}:
    post:
      summary: Invalidate cache entries
      description: |
        Manually invalidate cache entries of a specific type.
        Use sparingly - prefer automatic invalidation via CRUD operations.
      operationId: invalidateCache
      tags:
        - Cache Management
      security:
        - bearerAuth: []
      parameters:
        - name: cacheType
          in: path
          required: true
          description: Type of cache to invalidate
          schema:
            type: string
            enum: [trucks, drivers, groups, stats, all]
        - name: groupId
          in: query
          required: false
          description: Optional group ID to scope invalidation
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Cache invalidated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidationResult'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - requires FLEET_MANAGER role

  /health:
    get:
      summary: Check cache health
      description: Returns Redis connection status and cache availability
      operationId: getCacheHealth
      tags:
        - Cache Management
      responses:
        '200':
          description: Cache is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CacheHealth'
        '503':
          description: Cache unavailable (Redis down)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CacheHealth'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CacheStats:
      type: object
      properties:
        caches:
          type: array
          items:
            $ref: '#/components/schemas/CacheTypeStats'
        totalKeys:
          type: integer
          description: Total number of cached keys
          example: 156
        memoryUsedBytes:
          type: integer
          description: Redis memory used for caching
          example: 2457600
        hitRate:
          type: number
          format: float
          description: Overall cache hit rate (0.0 to 1.0)
          example: 0.87
        uptime:
          type: string
          description: Time since last Redis restart
          example: "7d 4h 23m"

    CacheTypeStats:
      type: object
      properties:
        type:
          type: string
          enum: [trucks, drivers, groups, stats]
        keyCount:
          type: integer
          example: 45
        hitCount:
          type: integer
          example: 1250
        missCount:
          type: integer
          example: 180
        ttlSeconds:
          type: integer
          example: 300
        avgSizeBytes:
          type: integer
          example: 5120

    InvalidationResult:
      type: object
      properties:
        cacheType:
          type: string
          example: "trucks"
        keysInvalidated:
          type: integer
          example: 23
        timestamp:
          type: string
          format: date-time
          example: "2025-12-26T15:30:00Z"

    CacheHealth:
      type: object
      properties:
        status:
          type: string
          enum: [UP, DOWN, DEGRADED]
        redisConnected:
          type: boolean
        fallbackActive:
          type: boolean
          description: True if currently falling back to database
        lastError:
          type: string
          nullable: true
          description: Last error message if any
        checkedAt:
          type: string
          format: date-time
